### ISSUE TITLE
Add autofix option

### ISSUE THREAD

**Issue by arturtr** [ericqweinstein/ruumba#1]
Rubocop has autofix option `-a`. It is very useful for legacy projects.

Can you add it to `ruumba`?

**Comment by ericqweinstein** [comment]
@arturtr Sure! I'll make a PR over the holidays. Thanks for using Ruumba!

**Comment by SijiaDavis** [comment]
Hi! I'd also like to have this option added to Ruumba, just wondering if there's any update on this?

**Comment by ericqweinstein** [comment]
@arturtr @SijiaDavis Ah, apologies! I started a branch for this and never finished it. I should be able to get to it this weekend; please bug me again if you don't see a PR next week. 👍

**Comment by SijiaDavis** [comment]
Hi @ericqweinstein, any updates on the PR? let me know if I can help 😁! Thanks!

**Comment by ericqweinstein** [comment]
@SijiaDavis Thanks for checking in! Will be up tonight, thanks so much for your patience :)

**Comment by ericqweinstein** [comment]
@SijiaDavis Opened #4. Let me know what you think!

**Comment by aclemons** [comment]
Any takers on testing / reviewing this change?
