### ISSUE TITLE
Use default configuration file .ruumba.yml.

### ISSUE THREAD

**Issue by matthewtuck** [ericqweinstein/ruumba#26]
If you don't specify a config file on the command line, Rubocop will use the default of .rubocop.yml if it exists.

It would be nice if Ruumba would look at .ruumba.yml by default if it exists.

**Comment by aclemons** [comment]
I don't see an issue with doing this. I've opened a PR (https://github.com/ericqweinstein/ruumba/pull/31) for it. Thoughts @ericqweinstein ?
