### ISSUE TITLE
Clarification on the project purpose

### ISSUE THREAD

**Issue by fidalgo** [ericqweinstein/ruumba#47]
Don't take this as offensive, but since there's an already old project https://github.com/Shopify/erb-lint can you enlight the differences on ruumba, or ultimately why do you created a new project for doing the same (as it seems).

**Comment by ericqweinstein** [comment]
Thanks for your comment! Ruumba was open-sourced on April 26, 2015 (and was started earlier); erb-lint dates back to May 9, 2016.
